//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH_AN
    {
        public string MaBenhAn { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string TrieuChung { get; set; }
        public string ChanDoan { get; set; }
        public string DonThuoc { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
        public string MaPet { get; set; }
        public string MaBacSi { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual THU_CUNG THU_CUNG { get; set; }
    }
}
