//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_LICH_HEN
    {
        public int MaChiTietLH { get; set; }
        public string MaLichHen { get; set; }
        public string GhiChu { get; set; }
        public string MaDV { get; set; }
    
        public virtual LICH_HEN LICH_HEN { get; set; }
        public virtual DICH_VU DICH_VU { get; set; }
    }
}
