//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_PHIEU_KHO
    {
        public int MaChiTietPhieu { get; set; }
        public string MaPhieu { get; set; }
        public string MaSanPham { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual PHIEU_KHO PHIEU_KHO { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
