//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANG_KY_GOI
    {
        public int MaDangKy { get; set; }
        public string MaKH { get; set; }
        public string MaGoi { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual GOI_DINH_KY GOI_DINH_KY { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
