//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_HEN
    {
        public int MaLichHen { get; set; }
        public System.DateTime NgayHen { get; set; }
        public System.TimeSpan GioHen { get; set; }
        public string TrangThai { get; set; }
        public string LyDoTuChoi { get; set; }
        public int MaKH { get; set; }
        public int MaPet { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual DICH_VU DICH_VU { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual THU_CUNG THU_CUNG { get; set; }
    }
}
