//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_HEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICH_HEN()
        {
            this.DICH_VU = new HashSet<DICH_VU>();
        }
    
        public int MaLichHen { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string ChiNhanh { get; set; }
        public System.DateTime NgayHen { get; set; }
        public System.TimeSpan GioHen { get; set; }
        public string TrangThai { get; set; }
        public string LyDoTuChoi { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPet { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICH_VU> DICH_VU { get; set; }
    }
}
