//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_HEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICH_HEN()
        {
            this.CHI_TIET_LICH_HEN = new HashSet<CHI_TIET_LICH_HEN>();
        }
    
        public string MaLichHen { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string ChiNhanH { get; set; }
        public System.DateTime NgayHen { get; set; }
        public string GioHen { get; set; }
        public string TrangThai { get; set; }
        public string LyDoTuChoi { get; set; }
        public string MaKH { get; set; }
        public string MaPet { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_LICH_HEN> CHI_TIET_LICH_HEN { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual THU_CUNG THU_CUNG { get; set; }
        public virtual KHACH_HANG KHACH_HANG1 { get; set; }
    }
}
