//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_HOAT_DONG
    {
        public int MaLog { get; set; }
        public string MaTaiKhoan { get; set; }
        public string HanhDong { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string IpAddress { get; set; }
    
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
