//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAI_KHOAN()
        {
            this.KHACH_HANG = new HashSet<KHACH_HANG>();
            this.LOG_HOAT_DONG = new HashSet<LOG_HOAT_DONG>();
            this.NHAN_VIEN = new HashSet<NHAN_VIEN>();
            this.TIN_NHAN_CHAT = new HashSet<TIN_NHAN_CHAT>();
            this.TIN_NHAN_CHAT1 = new HashSet<TIN_NHAN_CHAT>();
        }
    
        public string MaTaiKhoan { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string VaiTro { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACH_HANG> KHACH_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_HOAT_DONG> LOG_HOAT_DONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAN_VIEN> NHAN_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIN_NHAN_CHAT> TIN_NHAN_CHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIN_NHAN_CHAT> TIN_NHAN_CHAT1 { get; set; }
    }
}
