//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THU_CUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THU_CUNG()
        {
            this.BENH_AN = new HashSet<BENH_AN>();
            this.LICH_HEN = new HashSet<LICH_HEN>();
        }
    
        public int MaPet { get; set; }
        public string TenPet { get; set; }
        public string ChungLoai { get; set; }
        public string GiongPet { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<double> CanNang { get; set; }
        public int MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENH_AN> BENH_AN { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_HEN> LICH_HEN { get; set; }
    }
}
