//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_NHAN_CHAT
    {
        public int MaTinNhan { get; set; }
        public string MaTaiKhoanGui { get; set; }
        public string MaTaiKhoanNhan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
    
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN1 { get; set; }
    }
}
